name: push

on:
    push:
        paths:
            - "**.md"

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Run a script
              run: echo "push event"
    hello:
        uses: ./.github/workflows/reusable.yml